name: docker push ci-cd
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: install dependencies
        run : npm install
      - name: run tests
        run : npm test

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build docekr image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/vidisha162:latest .
      - name: push docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/vidisha162:latest
